check: teams

diff --git a/.github/workflows/01azure_deploy.yml b/.github/workflows/01azure_deploy.yml
--- a/.github/workflows/01azure_deploy.yml
+++ b/.github/workflows/01azure_deploy.yml
@@ -198,6 +198,8 @@ jobs:
     runs-on: ubuntu-latest
     needs: setup_failure
     if: always()
+    outputs:
+      status_azure_deploy: ${{ steps.set_outputs.outputs.status_azure_deploy }}
     steps:
       # job azure_deploy の結果を得る
       #- name: Getting azure_deploy result
@@ -218,11 +220,13 @@ jobs:
           echo "::set-output name=status_azure_deploy::$(<pass_status_azure_deploy/status_azure_deploy.txt)"
           echo "::set-output name=pass_status_azure_deploy::$(<pass_status_azure_deploy/status_azure_deploy.txt)"
       - name: check_failure
-        if: ${{ steps.set_outputs.outputs.status_azure_deploy }} == 'failure'
+        #if: ${{ steps.set_outputs.outputs.status_azure_deploy }} == 'failure'
         run: | 
             echo "status_azure_deploy: $status_azure_deploy"
             echo "pass_status_azure_deploy: $pass_status_azure_deploy"
-            exit 1
+            if [ status_azure_deploy == failure ]; then
+              exit 1
+            fi
       - name: Microsoft Teams Notification
         uses: skitionek/notify-microsoft-teams@master
         #if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure
