check: teams

diff --git a/.github/workflows/01azure_deploy.yml b/.github/workflows/01azure_deploy.yml
--- a/.github/workflows/01azure_deploy.yml
+++ b/.github/workflows/01azure_deploy.yml
@@ -221,7 +221,10 @@ jobs:
           echo "::set-output name=pass_status_azure_deploy::$(<pass_status_azure_deploy/status_azure_deploy.txt)"
       - name: check_failure
         #if: ${{ steps.set_outputs.outputs.status_azure_deploy }} == 'failure'
-        run: | 
+        if: ${{ needs.deploy_failure.outputs.azure_deploy }} == 'failure'
+        run: |
+            echo "xx: ${{ needs.deploy_failure.outputs.azure_deploy }}"
+            exit 1
             echo "status_azure_deploy: $status_azure_deploy"
             echo "pass_status_azure_deploy: $pass_status_azure_deploy"
             echo "needs.deploy_failure.outputs.azure_deploy: ${{ needs.deploy_failure.outputs.azure_deploy }}"
